### ISSUE TITLE
normalize.TGGATES ?

### ISSUE THREAD

**Issue by vittoriofortino84** [bhaibeka/TGGATES#1]
Where is "normalize.TGGATES" located?

Thanks!

Br

**Comment by bhaibeka** [comment]
It is in an old version of PharmacoGx but has been removed since. Look at this page for all the files: https://www.pmgenomics.ca/bhklab/pubs/tggates

PharmacoGx version 0.0.3 is available from here: https://www.pmgenomics.ca/bhklab/sites/default/files/downloads/PharmacoGx_0.0.3.tar.gz
